# Generated by Django 2.1.7 on 2019-03-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaiwalaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChaiwalaReg_Model',
            new_name='Reg_Model',
        ),
        migrations.DeleteModel(
            name='CustomerReg_Model',
        ),
    ]
