# Generated by Django 2.1.7 on 2019-03-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaiwalaapp', '0003_auto_20190314_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
