# Generated by Django 2.1.7 on 2019-03-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaiwalaapp', '0005_chai_order_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chai_order_model',
            name='User',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
